// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeSc5ve2weKPGSk4Exgy5-VTBa4fGNPZQ',
    appId: '1:884254413846:web:bd13599244d7ec7abe5137',
    messagingSenderId: '884254413846',
    projectId: 'smartdoorbell-32ea3',
    authDomain: 'smartdoorbell-32ea3.firebaseapp.com',
    databaseURL: 'https://smartdoorbell-32ea3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdoorbell-32ea3.appspot.com',
    measurementId: 'G-BBW763ZCEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq4_QnTuC7q9RVkI6q99kdwgNHXix4Ev0',
    appId: '1:884254413846:android:7ebb2e114ea45403be5137',
    messagingSenderId: '884254413846',
    projectId: 'smartdoorbell-32ea3',
    databaseURL: 'https://smartdoorbell-32ea3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdoorbell-32ea3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOGR0XOBDJgVf9HXhoUUM8JdQf5HecEj0',
    appId: '1:884254413846:ios:373f19eaadd8c4fbbe5137',
    messagingSenderId: '884254413846',
    projectId: 'smartdoorbell-32ea3',
    databaseURL: 'https://smartdoorbell-32ea3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdoorbell-32ea3.appspot.com',
    iosBundleId: 'com.example.smartdoorbellApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOGR0XOBDJgVf9HXhoUUM8JdQf5HecEj0',
    appId: '1:884254413846:ios:061abb9729025153be5137',
    messagingSenderId: '884254413846',
    projectId: 'smartdoorbell-32ea3',
    databaseURL: 'https://smartdoorbell-32ea3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdoorbell-32ea3.appspot.com',
    iosBundleId: 'com.example.smartdoorbellApp.RunnerTests',
  );
}
